[package]
name = "tai"
version = "0.1.0"
edition = "2021"

[dependencies]
# error handling
anyhow = "1.0"

# async
tokio = { version = "1.40", features = ["macros", "rt-multi-thread", "fs", "signal", "rt"] }
futures = "0.3"

spinoff = "0.8"
rllm = { version = "1.1", features = ["openai", "anthropic", "ollama"] }

# de/serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
