[package]
name = "tai"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "cargo"] }
tokio = { version = "1.40", features = ["macros", "rt-multi-thread", "fs", "signal", "rt"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
futures = "0.3"
spinoff = "0.8"
llm = { version = "1.2", features = ["openai", "anthropic", "ollama", "google", "azure_openai"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"
walkdir = "2.5"
ignore = "0.4"
globset = "0.4"
regex = "1.10"
arboard = "3.4"
syntect = "5"
once_cell = "1.19"
pulldown-cmark = { version = "0.9", default-features = true }
nu-ansi-term = "0.50"
