[package]
name = "tai"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
indicatif = "0.17"
rllm = { version = "1.1.0", features = ["openai", "anthropic", "ollama"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
